# -*- coding: utf-8 -*-
"""Cópia de ajusteBrilhoipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eRY8nHwOfoK5Z-HKDjIpCGQqHGtKSEHo

# Aumentando o brilho de uma imagem com python e opencv

## importe as bibliotecas necessárias
- opencv - biblioteca de processamento de imagem
- numpy - necessária para criar a imagem de brilho
- cv2_imshow - para o google colab mostrar as imagens
"""

import cv2 
# from google.colab.patches import cv2_imshow
import numpy as np

"""## Leia a imagem"""

#caminho da imagem
imagePath = 'Fruit-Vegetable-Processing.jpg'

#link para a imagem utilizar - https://www.jbtc.com/foodtech/wp-content/uploads/sites/2/2021/08/Fruit-Vegetable-Processing.jpg

#lendo a imagem 
image = cv2.imread(imagePath)

""" Crie a matriz de brilho onde cada ponto será (100,100,100) e adicione a imagem original 
Lembrando que o valor máximo do pixel no espaço RGB é 255.
"""

#criando image imagem do mesmo tamanho para ser o 'brilho'
bright = np.zeros_like(image)
#adicionaremos um brilho de 100 em cada pixel
bright[:,:,:] = [0,100,100] # (b,g,r)
#some 100 em cada pixel da imagem
brilho = cv2.add(image, bright)
#caso a soma ultrapasse 255 (máximo), limite-o a 255 (branco)
brilho[brilho > 255] = 255

#mostre a imagem original
cv2.imshow('Original', image)
#mostre a imagem de brilho
cv2.imshow('Brilho', brilho)
#espere um comando
cv2.waitKey()